# Site settings
title: "기록도 록이다" # 블로그 제목
description: "기록도 록이다" # 블로그 설명
baseurl: "" # GitHub Pages에서 루트에 위치할 경우 빈 문자열로 설정
url: "https://023-dev.github.io" # 블로그 URL

# Google Analytics
google_analytics: "G-LDJQ09Q3V9" # 자신의 Google Analytics 코드로 대체 (필요한 경우)

# Author
author:
  name: "023" # 블로그 작성자 이름
  url: "https://github.com/023-dev" # 개인 웹사이트 (필요한 경우)
  email: "rhdgmltkd88@gmail.com" # 이메일 주소 (필요한 경우)

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji # 이모지를 사용하려면 주석을 해제

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Comments (Utterances 설정)
comments:
  provider: "utterances"
  repo: "023-dev/023-dev.github.io" # GitHub 댓글 저장소 (예: 023-dev/023-dev.github.io)
  issue_term: "pathname" # 게시물 경로별로 댓글 연결
  label: "comment" # 댓글의 GitHub 라벨 (선택 사항)
  theme: "github-light" # Utterances 테마 (github-light 또는 github-dark 등)

# Disqus 설정 (사용하지 않으므로 제거 가능)
# disqus: "my-disqus-id"