module.exports = {
  title: "hoodie",
  description: "Hello :) I'm Hudi who developed gatsby-starter-hoodie theme.",
  author: "Hudi",
  siteUrl: "https://023-dev.github.io/",
  links: {
    github: "https://github.com/devHudi",
    linkedIn: "https://linkedin.com",
    facebook: "https://www.facebook.com",
    twitter: "https://twitter.com",
    x: "https://x.com",
    instagram: "https://www.instagram.com",
    medium: "https://medium.com",
    blogger: "https://blogger.com",
    email: "mailto:devhudi@gmail.com",
    resume: "https://hudi.blog",
    link: "https://hudi.blog",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "023-dev/023-dev.github.io",
    repoId: "R_kgDONKt8Yg=",
    category: "Announcements",
    categoryId: "DIC_kwDONKt8Ys4Cll2b",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
